CREATE USER mcp_owner WITH PASSWORD '99LofZCa3OURoBDVvhUdT8SxF9kRA7eF';
CREATE USER mcp_readonly WITH PASSWORD 'e37CQ6uYzN3BanTZL4J0ArPKeZPI820C';

CREATE DATABASE rag_vectordb OWNER mcp_owner;

\c rag_vectordb

CREATE EXTENSION IF NOT EXISTS vector;

GRANT CONNECT ON DATABASE rag_vectordb TO mcp_readonly;
GRANT USAGE ON SCHEMA public TO mcp_readonly;
GRANT SELECT ON ALL TABLES IN SCHEMA public TO mcp_readonly;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT ON TABLES TO mcp_readonly;
