from __future__ import annotations

from app.command_policy import DestructivePattern, PatternSuggestion, Severity
from app.packs import Pack

# Every DestructivePattern verbatim from command_policy.py's CLOUD_DESTRUCTIVE_PATTERNS
# AWS (19) + GCP (16) + Azure (15) = 50 patterns

CLOUD_PATTERNS: tuple[DestructivePattern, ...] = (
    # ---- AWS CLI ----
    DestructivePattern(
        name="aws-ec2-terminate",
        regex=r"aws\b.*?\bec2\s+terminate-instances",
        reason="aws ec2 terminate-instances permanently destroys EC2 instances",
        severity=Severity.CRITICAL,
        description="Instance is stopped and deleted. EBS volumes and Elastic IPs are lost.",
        suggestions=(
            PatternSuggestion("aws ec2 stop-instances --instance-ids i-xxx",
                              "Stop instead of terminate for recoverable pause"),
            PatternSuggestion("aws ec2 describe-instances --instance-ids i-xxx",
                              "Verify instance details before terminating"),
        ),
    ),
    DestructivePattern(
        name="aws-ec2-delete",
        regex=r"aws\b.*?\bec2\s+delete-",
        reason="aws ec2 delete-* permanently removes EC2 resources (snapshots, volumes, VPCs, AMIs)",
        severity=Severity.HIGH,
        description="EC2 delete commands: delete-snapshot, delete-volume, delete-vpc, delete-image.",
        suggestions=(),
    ),
    DestructivePattern(
        name="aws-s3-rm-recursive",
        regex=r"aws\b.*?\bs3\s+rm\s+.*--recursive",
        reason="aws s3 rm --recursive permanently deletes ALL objects in the S3 path",
        severity=Severity.CRITICAL,
        description="Recursive deletion of all objects under the prefix. "
        "No recovery unless bucket versioning is enabled.",
        suggestions=(
            PatternSuggestion("aws s3 rm s3://bucket/path/ --recursive --dryrun",
                              "Preview deletions with --dryrun"),
            PatternSuggestion("aws s3 ls s3://bucket/path/ --recursive",
                              "List objects to verify before deleting"),
        ),
    ),
    DestructivePattern(
        name="aws-s3-rb",
        regex=r"aws\b.*?\bs3\s+rb\b",
        reason="aws s3 rb removes the entire S3 bucket",
        severity=Severity.CRITICAL,
        description="rb removes an S3 bucket. With --force, deletes all contents first.",
        suggestions=(),
    ),
    DestructivePattern(
        name="aws-s3api-delete-bucket",
        regex=r"aws\b.*?\bs3api\s+delete-bucket",
        reason="aws s3api delete-bucket removes the S3 bucket",
        severity=Severity.CRITICAL,
        description="Bucket must be empty. Check contents before deleting.",
        suggestions=(),
    ),
    DestructivePattern(
        name="aws-s3api-delete-object",
        regex=r"aws\b.*?\bs3api\s+delete-object",
        reason="aws s3api delete-object[s] permanently removes objects unless versioning is enabled",
        severity=Severity.HIGH,
        description="delete-objects is BATCH (up to 1000 keys). "
        "Without versioning, objects are permanently gone.",
        suggestions=(
            PatternSuggestion("aws s3api get-bucket-versioning --bucket xxx",
                              "Check if versioning is enabled first"),
        ),
    ),
    DestructivePattern(
        name="aws-rds-delete",
        regex=r"aws\b.*?\brds\s+delete-",
        reason="aws rds delete-* destroys database resources (instance, cluster, snapshot)",
        severity=Severity.CRITICAL,
        description="RDS delete commands remove database instances, clusters, and snapshots. "
        "Create a final snapshot before deletion.",
        suggestions=(),
    ),
    DestructivePattern(
        name="aws-cfn-delete-stack",
        regex=r"aws\b.*?\bcloudformation\s+delete-stack",
        reason="aws cloudformation delete-stack removes the stack and ALL resources it created",
        severity=Severity.CRITICAL,
        description="All EC2, RDS, S3, IAM resources created by the stack are deleted.",
        suggestions=(),
    ),
    DestructivePattern(
        name="aws-lambda-delete",
        regex=r"aws\b.*?\blambda\s+delete-",
        reason="aws lambda delete-* removes Lambda function, alias, or layer version",
        severity=Severity.HIGH,
        description="Function code, versions, aliases, and event source mappings are removed.",
        suggestions=(),
    ),
    DestructivePattern(
        name="aws-iam-delete",
        regex=r"aws\b.*?\biam\s+delete-",
        reason="aws iam delete-* removes IAM resources (user, role, policy, group)",
        severity=Severity.HIGH,
        description="IAM deletions break authentication for users and services using those resources.",
        suggestions=(),
    ),
    DestructivePattern(
        name="aws-dynamodb-delete",
        regex=r"aws\b.*?\bdynamodb\s+delete-table",
        reason="aws dynamodb delete-table permanently deletes the table and ALL data",
        severity=Severity.CRITICAL,
        description="All items, indexes, and table configuration are lost.",
        suggestions=(),
    ),
    DestructivePattern(
        name="aws-eks-delete",
        regex=r"aws\b.*?\beks\s+delete-cluster",
        reason="aws eks delete-cluster removes the entire EKS cluster",
        severity=Severity.CRITICAL,
        description="Control plane is deleted. Node groups must be deleted separately first.",
        suggestions=(),
    ),
    DestructivePattern(
        name="aws-ecr-delete-repository",
        regex=r"aws\b.*?\becr\s+delete-repository",
        reason="aws ecr delete-repository permanently deletes the repository and its images",
        severity=Severity.HIGH,
        description="All images in the repository are deleted.",
        suggestions=(),
    ),
    DestructivePattern(
        name="aws-kms-schedule-key-deletion",
        regex=r"aws\b.*?\bkms\s+schedule-key-deletion",
        reason="aws kms schedule-key-deletion schedules irreversible KMS key destruction",
        severity=Severity.CRITICAL,
        description="Data encrypted with this key becomes permanently undecryptable. "
        "CancelKeyDeletion can abort within the waiting window.",
        suggestions=(
            PatternSuggestion("aws kms disable-key --key-id xxx",
                              "Disable key instead of deletion for reversible deactivation"),
        ),
    ),
    DestructivePattern(
        name="aws-secretsmanager-delete-secret",
        regex=r"aws\b.*?\bsecretsmanager\s+delete-secret",
        reason="aws secretsmanager delete-secret destroys a stored secret",
        severity=Severity.CRITICAL,
        description="30-day recovery window unless --force-delete-without-recovery used.",
        suggestions=(),
    ),
    DestructivePattern(
        name="aws-route53-delete-hosted-zone",
        regex=r"aws\b.*?\broute53\s+delete-hosted-zone",
        reason="aws route53 delete-hosted-zone removes DNS zone — domains stop resolving",
        severity=Severity.CRITICAL,
        description="All DNS records deleted. Production traffic can become unroutable immediately.",
        suggestions=(
            PatternSuggestion("aws route53 list-resource-record-sets --hosted-zone-id xxx",
                              "Export records first"),
        ),
    ),
    DestructivePattern(
        name="aws-cloudtrail-delete-trail",
        regex=r"aws\b.*?\bcloudtrail\s+delete-trail",
        reason="aws cloudtrail delete-trail removes audit trail — compliance/forensics impact",
        severity=Severity.CRITICAL,
        description="Historical logs in S3 are preserved, but future events stop being recorded.",
        suggestions=(),
    ),
    DestructivePattern(
        name="aws-redshift-delete-cluster",
        regex=r"aws\b.*?\bredshift\s+delete-cluster",
        reason="aws redshift delete-cluster destroys Redshift cluster and all data",
        severity=Severity.CRITICAL,
        description="With --skip-final-cluster-snapshot, ALL data is destroyed immediately.",
        suggestions=(),
    ),
    DestructivePattern(
        name="aws-logs-delete-log-group",
        regex=r"aws\b.*?\blogs\s+delete-log-group",
        reason="aws logs delete-log-group permanently deletes log group and all events",
        severity=Severity.HIGH,
        description="All log streams, events, metric filters, and subscriptions are lost.",
        suggestions=(),
    ),
    # ---- GCP / gcloud CLI ----
    DestructivePattern(
        name="gcp-compute-delete",
        regex=r"gcloud\b.*?\bcompute\s+instances\s+delete",
        reason="gcloud compute instances delete permanently destroys VM instances",
        severity=Severity.CRITICAL,
        description="Boot disk deleted unless --keep-disks specified. External IPs released.",
        suggestions=(),
    ),
    DestructivePattern(
        name="gcp-disk-delete",
        regex=r"gcloud\b.*?\bcompute\s+disks\s+delete",
        reason="gcloud compute disks delete permanently destroys disk data",
        severity=Severity.CRITICAL,
        description="All data on disk is lost forever without snapshots.",
        suggestions=(),
    ),
    DestructivePattern(
        name="gcp-sql-delete",
        regex=r"gcloud\b.*?\bsql\s+instances\s+delete",
        reason="gcloud sql instances delete permanently destroys Cloud SQL instance",
        severity=Severity.CRITICAL,
        description="Database and all data deleted along with backups and read replicas.",
        suggestions=(),
    ),
    DestructivePattern(
        name="gcp-gsutil-rm-recursive",
        regex=r"gsutil\b.*?\brm\s+.*-r|gsutil\b.*?\brm\s+-[a-z]*r",
        reason="gsutil rm -r permanently deletes ALL objects in the GCS path",
        severity=Severity.CRITICAL,
        description="All objects under path deleted. No recovery without versioning.",
        suggestions=(
            PatternSuggestion("gsutil ls -r gs://bucket/path/",
                              "List objects first"),
            PatternSuggestion("gsutil versioning set on gs://bucket",
                              "Enable versioning for recovery"),
        ),
    ),
    DestructivePattern(
        name="gcp-gsutil-rb",
        regex=r"gsutil\b.*?\brb(?=\s|$)",
        reason="gsutil rb removes the entire GCS bucket",
        severity=Severity.CRITICAL,
        description="Bucket name becomes available to others. Bucket must be empty.",
        suggestions=(),
    ),
    DestructivePattern(
        name="gcp-gke-delete",
        regex=r"gcloud\b.*?\bcontainer\s+clusters\s+delete",
        reason="gcloud container clusters delete removes entire GKE cluster",
        severity=Severity.CRITICAL,
        description="All nodes and workloads terminated. Persistent volumes may be deleted.",
        suggestions=(),
    ),
    DestructivePattern(
        name="gcp-project-delete",
        regex=r"gcloud\b.*?\bprojects\s+delete",
        reason="gcloud projects delete removes the ENTIRE GCP project and ALL resources",
        severity=Severity.CRITICAL,
        description="ALL resources deleted: VMs, databases, storage, functions, IAM. "
        "30-day recovery window, then permanent.",
        suggestions=(),
    ),
    DestructivePattern(
        name="gcp-functions-delete",
        regex=r"gcloud\b.*?\bfunctions\s+delete",
        reason="gcloud functions delete removes Cloud Function",
        severity=Severity.HIGH,
        description="Function code, configuration, triggers, and event subscriptions removed.",
        suggestions=(),
    ),
    DestructivePattern(
        name="gcp-firestore-delete",
        regex=r"gcloud\b.*?\bfirestore\s+.*delete",
        reason="gcloud firestore delete removes Firestore documents and collections",
        severity=Severity.CRITICAL,
        description="Documents and collections deleted. No automatic backups by default.",
        suggestions=(),
    ),
    DestructivePattern(
        name="gcp-secrets-delete",
        regex=r"gcloud\b.*?\bsecrets\s+delete",
        reason="gcloud secrets delete destroys a Secret Manager secret",
        severity=Severity.CRITICAL,
        description="Secret and ALL versions permanently deleted. No recovery window.",
        suggestions=(),
    ),
    DestructivePattern(
        name="gcp-kms-keys-destroy",
        regex=r"gcloud\b.*?\bkms\s+keys\s+versions\s+destroy",
        reason="gcloud kms keys versions destroy schedules key version destruction",
        severity=Severity.CRITICAL,
        description="Data encrypted under this key version becomes unrecoverable.",
        suggestions=(),
    ),
    DestructivePattern(
        name="gcp-iam-service-accounts-delete",
        regex=r"gcloud\b.*?\biam\s+service-accounts\s+delete",
        reason="gcloud iam service-accounts delete removes a service account",
        severity=Severity.CRITICAL,
        description="Workloads using this SA lose access. Can undelete within 30 days.",
        suggestions=(),
    ),
    DestructivePattern(
        name="gcp-dns-managed-zones-delete",
        regex=r"gcloud\b.*?\bdns\s+managed-zones\s+delete",
        reason="gcloud dns managed-zones delete removes DNS zone — domains stop resolving",
        severity=Severity.CRITICAL,
        description="All record sets deleted. Production traffic can go dark.",
        suggestions=(),
    ),
    DestructivePattern(
        name="gcp-spanner-instances-delete",
        regex=r"gcloud\b.*?\bspanner\s+instances\s+delete",
        reason="gcloud spanner instances delete destroys Spanner instance and all data",
        severity=Severity.CRITICAL,
        description="All databases inside instance deleted. Unrecoverable without export.",
        suggestions=(),
    ),
    DestructivePattern(
        name="gcp-bigtable-instances-delete",
        regex=r"gcloud\b.*?\bbigtable\s+instances\s+delete",
        reason="gcloud bigtable instances delete destroys Bigtable instance and all data",
        severity=Severity.CRITICAL,
        description="All tables, clusters, and data permanently deleted.",
        suggestions=(),
    ),
    DestructivePattern(
        name="gcp-bq-rm-recursive",
        regex=r"\bbq\b.*?\brm\s+.*-r\b|\bbq\b.*?\brm\s+.*-f\b",
        reason="bq rm -r/-f removes BigQuery datasets, tables — data lost",
        severity=Severity.CRITICAL,
        description="bq rm -r removes dataset + ALL tables/views/models inside. "
        "bq rm -f removes table without confirmation.",
        suggestions=(),
    ),
    # ---- Azure / az CLI ----
    DestructivePattern(
        name="az-vm-delete",
        regex=r"az\b.*?\bvm\s+delete",
        reason="az vm delete permanently destroys virtual machines",
        severity=Severity.CRITICAL,
        description="VM deallocated and deleted. OS disk deleted unless --os-disk=detach.",
        suggestions=(),
    ),
    DestructivePattern(
        name="az-storage-delete",
        regex=r"az\b.*?\bstorage\s+account\s+delete",
        reason="az storage account delete destroys storage account and ALL data",
        severity=Severity.CRITICAL,
        description="ALL blobs, files, queues, tables deleted. Unrecoverable.",
        suggestions=(),
    ),
    DestructivePattern(
        name="az-blob-delete",
        regex=r"az\b.*?\bstorage\s+(?:blob|container)\s+delete",
        reason="az storage blob/container delete permanently removes data",
        severity=Severity.HIGH,
        description="Blob delete removes individual blobs. Container delete removes ALL blobs.",
        suggestions=(),
    ),
    DestructivePattern(
        name="az-sql-delete",
        regex=r"az\b.*?\bsql\s+(?:server|db)\s+delete",
        reason="az sql server/db delete permanently destroys the database",
        severity=Severity.CRITICAL,
        description="Server delete removes ALL databases. Database delete removes specific DB.",
        suggestions=(),
    ),
    DestructivePattern(
        name="az-group-delete",
        regex=r"az\b.*?\bgroup\s+delete",
        reason="az group delete removes entire resource group and ALL resources within it",
        severity=Severity.CRITICAL,
        description="ALL resources in the group deleted: VMs, storage, databases, networks.",
        suggestions=(),
    ),
    DestructivePattern(
        name="az-aks-delete",
        regex=r"az\b.*?\baks\s+delete",
        reason="az aks delete removes entire AKS Kubernetes cluster",
        severity=Severity.CRITICAL,
        description="All nodes, workloads, load balancers terminated. Node resource group deleted.",
        suggestions=(),
    ),
    DestructivePattern(
        name="az-webapp-delete",
        regex=r"az\b.*?\bwebapp\s+delete",
        reason="az webapp delete removes App Service",
        severity=Severity.HIGH,
        description="Application code, configuration, custom domains, and SSL certificates removed.",
        suggestions=(),
    ),
    DestructivePattern(
        name="az-cosmosdb-delete",
        regex=r"az\b.*?\bcosmosdb\s+(?:delete|database\s+delete|collection\s+delete)",
        reason="az cosmosdb delete destroys Cosmos DB resources and data",
        severity=Severity.CRITICAL,
        description="Account delete removes entire Cosmos DB. Database/collection delete removes data.",
        suggestions=(),
    ),
    DestructivePattern(
        name="az-keyvault-delete",
        regex=r"az\b.*?\bkeyvault\s+delete",
        reason="az keyvault delete removes Key Vault — secrets may be unrecoverable",
        severity=Severity.CRITICAL,
        description="All secrets, keys, certificates deleted. Soft delete allows recovery if enabled.",
        suggestions=(),
    ),
    DestructivePattern(
        name="az-acr-delete",
        regex=r"az\b.*?\bacr\s+delete",
        reason="az acr delete removes container registry and ALL images",
        severity=Severity.CRITICAL,
        description="ALL repositories and images deleted. Registry name becomes available.",
        suggestions=(),
    ),
    DestructivePattern(
        name="az-acr-repository-delete",
        regex=r"az\b.*?\bacr\s+repository\s+delete",
        reason="az acr repository delete permanently deletes repository and its images",
        severity=Severity.HIGH,
        description="All tags and images in the repository deleted. New pulls will fail.",
        suggestions=(),
    ),
    DestructivePattern(
        name="az-keyvault-item-delete-or-purge",
        regex=r"az\b.*?\bkeyvault\s+(?:key|secret|certificate|storage)\s+(?:delete|purge)",
        reason="Key Vault item delete/purge — purge bypasses soft-delete and is irreversible",
        severity=Severity.CRITICAL,
        description="Purge is PERMANENT. Applications/services bound to the item fail immediately.",
        suggestions=(),
    ),
    DestructivePattern(
        name="az-ad-sp-delete",
        regex=r"az\b.*?\bad\s+sp\s+delete",
        reason="az ad sp delete removes service principal — workloads using it lose auth",
        severity=Severity.CRITICAL,
        description="All workloads authenticating via this SP lose access. "
        "Can restore within 30 days via Graph API.",
        suggestions=(),
    ),
    DestructivePattern(
        name="az-ad-app-delete",
        regex=r"az\b.*?\bad\s+app\s+delete",
        reason="az ad app delete removes Azure AD app registration — all SPs break",
        severity=Severity.CRITICAL,
        description="All service principals derived from this app stop working. "
        "OAuth grants invalidated.",
        suggestions=(),
    ),
    DestructivePattern(
        name="az-network-dns-zone-delete",
        regex=r"az\b.*?\bnetwork\s+dns\s+zone\s+delete",
        reason="az network dns zone delete removes DNS zone — domains stop resolving",
        severity=Severity.CRITICAL,
        description="All record sets deleted. Production traffic goes dark.",
        suggestions=(),
    ),
)


def build_cloud_pack() -> Pack:
    return Pack(id="cloud", name="Cloud CLI patterns",
        destructive_patterns=CLOUD_PATTERNS,
        keywords=("aws", "gcloud", "az", "gsutil", "bq"),
    )
