from __future__ import annotations

from app.command_policy import DestructivePattern, PatternSuggestion, Severity
from app.packs import Pack

DOCKER_PATTERNS: tuple[DestructivePattern, ...] = (
    DestructivePattern(name="system-prune",
        regex=r"docker\b.*?\bsystem\s+prune",
        reason="docker system prune removes ALL unused containers, networks, images, and build cache",
        severity=Severity.HIGH,
        description="docker system prune is Docker's most aggressive cleanup command.",
        suggestions=(PatternSuggestion("docker system df -v", "Preview without deleting"),)),
    DestructivePattern(name="volume-prune",
        regex=r"docker\b.*?\bvolume\s+prune",
        reason="docker volume prune permanently deletes ALL unused volumes and their data",
        severity=Severity.HIGH,
        description="Deletes all volumes not attached to a running container.",
        suggestions=(PatternSuggestion("docker volume ls", "List all volumes first"),)),
    DestructivePattern(name="network-prune",
        regex=r"docker\b.*?\bnetwork\s+prune",
        reason="docker network prune removes ALL unused networks",
        severity=Severity.HIGH,
        description="Removes all user-defined networks not used by containers.",
        suggestions=(PatternSuggestion("docker network ls", "List networks before pruning"),)),
    DestructivePattern(name="image-prune",
        regex=r"docker\b.*?\bimage\s+prune",
        reason="docker image prune removes unused (dangling) images",
        severity=Severity.MEDIUM,
        description="Removes dangling images. With -a flag, removes ALL unused images.",
        suggestions=(PatternSuggestion("docker images -f dangling=true", "List dangling images first"),)),
    DestructivePattern(name="container-prune",
        regex=r"docker\b.*?\bcontainer\s+prune",
        reason="docker container prune removes ALL stopped containers",
        severity=Severity.MEDIUM,
        description="Container logs and filesystem layers are lost.",
        suggestions=(PatternSuggestion("docker ps -a -f status=exited", "List stopped containers first"),)),
    DestructivePattern(name="rm-force",
        regex=r"docker\b.*?\brm\s+.*(?:-[a-zA-Z0-9]*f|--force)",
        reason="docker rm -f forcibly removes containers without graceful shutdown",
        severity=Severity.HIGH,
        description="Sends SIGKILL instead of SIGTERM.",
        suggestions=(PatternSuggestion("docker stop <c> && docker rm <c>", "Graceful shutdown"),)),
    DestructivePattern(name="rmi-force",
        regex=r"docker\b.*?\brmi\s+.*(?:-[a-zA-Z0-9]*f|--force)",
        reason="docker rmi -f forcibly removes images even if in use by containers",
        severity=Severity.HIGH,
        description="Forces image removal, potentially breaking running containers.",
        suggestions=(PatternSuggestion("docker rmi <image>", "Remove without force"),)),
    DestructivePattern(name="volume-rm",
        regex=r"docker\b.*?\bvolume\s+rm",
        reason="docker volume rm permanently deletes volumes and their data",
        severity=Severity.HIGH,
        description="Database files, uploads, and configuration volume data lost forever.",
        suggestions=(PatternSuggestion("docker volume inspect <volume>", "Inspect volume metadata first"),)),
    DestructivePattern(name="stop-all",
        regex=r"docker\b.*?\b(?:stop|kill)\s+\$\(",
        reason="Stopping/killing all containers can disrupt running services",
        severity=Severity.HIGH,
        description="Stops/kills ALL running containers via command substitution.",
        suggestions=(PatternSuggestion("docker stop <container>", "Stop specific containers"),)),
    DestructivePattern(name="builder-prune",
        regex=r"docker\b.*?\bbuilder\s+prune",
        reason="docker builder prune removes ALL build cache — rebuilds will be slow",
        severity=Severity.MEDIUM,
        description="Removes the entire build cache layer. All images must be rebuilt from scratch.",
        suggestions=(PatternSuggestion("docker builder ls", "List builders first"),)),
    DestructivePattern(name="network-rm",
        regex=r"docker\b.*?\bnetwork\s+rm\b",
        reason="docker network rm can break connectivity between running containers",
        severity=Severity.HIGH,
        description="Removing a network currently in use by containers will disconnect them.",
        suggestions=(PatternSuggestion("docker network inspect <name>", "Check which containers use it"),)),
)

COMPOSE_PATTERNS: tuple[DestructivePattern, ...] = (
    DestructivePattern(name="down-volumes",
        regex=r"(?:docker-compose|docker\s+compose)\s+down\s+.*(?:-v\b|--volumes)",
        reason="docker-compose down -v removes volumes and their data permanently",
        severity=Severity.CRITICAL,
        description="The -v flag removes named volumes declared in Compose.",
        suggestions=(PatternSuggestion("docker-compose down", "Stops without touching volumes"),)),
    DestructivePattern(name="down-rmi-all",
        regex=r"(?:docker-compose|docker\s+compose)\s+down\s+.*--rmi\s+all",
        reason="docker-compose down --rmi all removes all images used by services",
        severity=Severity.HIGH,
        description="All images must be re-pulled after this.",
        suggestions=(PatternSuggestion("docker-compose down", "Preserves images"),)),
    DestructivePattern(name="rm-volumes",
        regex=r"(?:docker-compose|docker\s+compose)\s+rm\s+.*(?:-v\b|--volumes)",
        reason="docker-compose rm -v removes volumes attached to containers",
        severity=Severity.HIGH,
        description="Anonymous volumes attached to containers are lost.",
        suggestions=(PatternSuggestion("docker-compose rm", "Preserves volumes"),)),
    DestructivePattern(name="compose-rm-force",
        regex=r"(?:docker-compose|docker\s+compose)\s+rm\s+.*(?:-f\b|--force)",
        reason="docker-compose rm -f forcibly removes containers without confirmation",
        severity=Severity.MEDIUM,
        description="Running containers are stopped abruptly (SIGKILL).",
        suggestions=(PatternSuggestion("docker-compose stop", "Graceful shutdown first"),)),
    DestructivePattern(name="compose-kill",
        regex=r"(?:docker-compose|docker\s+compose)\s+kill\b",
        reason="docker compose kill sends SIGKILL to all service containers",
        severity=Severity.MEDIUM,
        description="All containers are killed without graceful shutdown.",
        suggestions=(PatternSuggestion("docker-compose stop", "Graceful stop (SIGTERM) instead"),)),
)


def build_docker_pack() -> Pack:
    return Pack(id="docker", name="Docker patterns",
        destructive_patterns=DOCKER_PATTERNS + COMPOSE_PATTERNS,
        keywords=("docker", "docker-compose", "compose"),
    )
